





see_it_allasset_xplor_level0:
    path:     /1
    defaults: { _controller: SeeItAllassetXploreBundle:App:level0 }       


see_it_allasset_xplor_level1:
    path:     /1/{level0_id}   
    defaults: { _controller: SeeItAllassetXploreBundle:App:level1 }  
    requirements:
        level0_id:    \d+  

see_it_allasset_xplor_level2:
    path:     /1/{level0_id}/{level1_id}     
    defaults: { _controller: SeeItAllassetXploreBundle:App:level2 } 
    requirements:
        level0_id:    \d+ 
        level1_id:    \d+   # a digit of any length will match this route
           

see_it_allasset_xplor_level3:
    path:            /11/{level0_id}/{level1_id}/{level2_id}    
    defaults: { _controller: SeeItAllassetXploreBundle:App:level3 } 
    requirements: 
        level1_id:    \d+
        level2_id:    \d+
        level3_id:    \d+
       

see_it_allasset_xplor_level4:
    path:      /11/{level0_id}/{level1_id}/{level2_id}/{level3_id}       
    defaults: { _controller: SeeItAllassetXploreBundle:App:level4 }
    requirements: 
        level1_id:    \d+
        level2_id:    \d+
        level3_id:    \d+
        item_id:      \d+ 
  
 




#REMOVE ASSETS ROUTES

see_it_allasset_xplor_remove_level0:
    path:     /remove/1/{level0_id}    
    defaults: { _controller: SeeItAllassetXploreBundle:App:Removelevel0 }
    requirements: 
        level0_id:    \d+ 

see_it_allasset_xplor_remove_level1:
    path:     /remove/1/{level0_id} /{level1_id}    
    defaults: { _controller: SeeItAllassetXploreBundle:App:Removelevel1 }
    requirements:
        level0_id:    \d+ 
        level1_id:    \d+    

see_it_allasset_xplor_remove_level2:
    path:     /remove/1/{level0_id}/{level1_id}/{level2_id}     
    defaults: { _controller: SeeItAllassetXploreBundle:App:Removelevel2 }  
    requirements:
        level0_id:    \d+ 
        level1_id:    \d+
        level2_id:    \d+  
  
see_it_allasset_xplor_remove_level3:
    path:     /remove/1/{level0_id}/{level1_id}/{level2_id}/{level3_id}      
    defaults: { _controller: SeeItAllassetXploreBundle:App:Removelevel3}    
    requirements:
        level0_id:    \d+ 
        level1_id:    \d+
        level2_id:    \d+
        level3_id:    \d+

see_it_allasset_xplor_remove_level4:
    path:     /remove/1/{level0_id}/{level1_id}/{level2_id}/{level3_id}/{level4_id}       
    defaults: { _controller: SeeItAllassetXploreBundle:App:Removelevel4}    
    requirements:
        level0_id:    \d+ 
        level1_id:    \d+
        level2_id:    \d+
        level3_id:    \d+
        level4_id:    \d+




#DOCS ROUTES

see_it_allasset_xplor_level0_docs:
    path:     /level0/docs/{level0_id}    
    defaults: { _controller: SeeItAllassetXploreBundle:App:doclevel0 }
    requirements: 
        level1_id:    \d+  

see_it_allasset_xplor_level1_docs:
    path:     /level1/docs/{level1_id}    
    defaults: { _controller: SeeItAllassetXploreBundle:App:doclevel1 }
    requirements: 
        level0_id:    \d+
        level1_id:    \d+
        level2_id:    \d+    

see_it_allasset_xplor_level2_docs:
    path:     /docs/{level0_id}/{level1_id}/{level2_id}    
    defaults: { _controller: SeeItAllassetXploreBundle:App:doclevel2 } 
    requirements: 
        level0_id:    \d+
        level1_id:    \d+
        level2_id:    \d+   

see_it_allasset_xplor_level3_docs:
    path:     /docs/{level0_id}/{level1_id}/{level2_id}/{level3_id}      
    defaults: { _controller: SeeItAllassetXploreBundle:App:doclevel3 } 
    requirements: 
        level0_id:    \d+
        level1_id:    \d+
        level2_id:    \d+
        level3_id:    \d+

see_it_allasset_xplor_level4_docs:
    path:     /docs/{level0_id}/{level1_id}/{level2_id}/{level3_id}/{level4_id}      
    defaults: { _controller: SeeItAllassetXploreBundle:App:doclevel4 } 
    requirements: 
        level0_id:    \d+
        level1_id:    \d+
        level2_id:    \d+
        level3_id:    \d+
        level4_id:    \d+
        

 #REMOVE DOCS ROUTES


see_it_allasset_xplor_remove_level0_docs:
    path:     /remove/docs/1/{document_id}/{level0_id}    
    defaults: { _controller: SeeItAllassetXploreBundle:App:RemoveLevel0Doc }
    requirements: 
        document_id:   \d+
        level0_id:    \d+
        level1_id:    \d+   

see_it_allasset_xplor_remove_level1_docs:
    path:     /remove/docs/1/{document_id}/{level1_id}    
    defaults: { _controller: SeeItAllassetXploreBundle:App:Removelevel1Doc }
    requirements: 
        document_id:   \d+
        level0_id:    \d+
        level1_id:    \d+    

see_it_allasset_xplor_remove_level2_docs:
    path:     /remove/docs/1/{document_id}/{level0_id}/{level1_id}/{level2_id}     
    defaults: { _controller: SeeItAllassetXploreBundle:App:Removelevel2Doc }  
    requirements: 
        document_id:   \d+
        level0_id:    \d+
        level1_id:    \d+
        level2_id:    \d+  
  
see_it_allasset_xplor_remove_level3_docs:
    path:     /remove/docs/1/{document_id}/{level0_id}/{level1_id}/{level2_id}/{level3_id}      
    defaults: { _controller: SeeItAllassetXploreBundle:App:Removelevel3Doc}    
    requirements: 
        document_id:   \d+
        level0_id:    \d+
        level1_id:    \d+
        level2_id:    \d+
        level3_id:    \d+

see_it_allasset_xplor_remove_level4_docs:
    path:     /remove/docs/1/{document_id}/{level0_id}/{level1_id}/{level2_id}/{level3_id}/{level4_id}      
    defaults: { _controller: SeeItAllassetXploreBundle:App:Removelevel4Doc}    
    requirements: 
        document_id:   \d+
        level0_id:    \d+
        level1_id:    \d+
        level2_id:    \d+
        level3_id:    \d+
        level4_id:    \d+



#Loc ROUTES

see_it_allasset_xplor_level0_loc:
    path:     /loc/{level0_id}    
    defaults: { _controller: SeeItAllassetXploreBundle:App:loclevel0 }
    requirements: 
        level1_id:    \d+  


see_it_allasset_xplor_level2_grid:
    path:      /grid/{level1_id}/{level2_id}     
    defaults: { _controller: SeeItAllassetXploreBundle:App:gridlevel2}  
    requirements: 
        level1_id:    \d+
        level2_id:    \d+  


see_it_allasset_xplor_items_grid:
    path:      /grid/{level1_id}/{level2_id}/{item_id}       
    defaults: { _controller: SeeItAllassetXploreBundle:App:griditems}  
    requirements: 
        level1_id:    \d+
        level2_id:    \d+ 




